#!/bin/bash

#get secrets

#naemon install script Centos7
rpm -Uvh "https://labs.consol.de/repo/stable/rhel7/i386/labs-consol-stable.rhel7.noarch.rpm"
yes | amazon-linux-extras install epel
yes | yum install naemon*
yum -y install nagios-plugins nagios-plugins-all nagios-plugins-nrpe nrpe
chkconfig httpd on && service httpd start
chkconfig naemon on && service naemon start
chkconfig thruk on && service thruk start
echo $nagiosadmin | htpasswd -c -i /etc/thruk/htpasswd thrukadmin
# End Install
